### ISSUE TITLE
JAMF PRO 10.8.0

### ISSUE THREAD

**Issue by AllWorkAndNoPlay** [jssimporter/jss_helper#25]
jss_helper fails connect properly with JAMF PRO 10.8.0

`jss_helper promote

Traceback (most recent call last):
  File "/usr/local/bin/jss_helper", line 107, in <module>
    main()
  File "/usr/local/bin/jss_helper", line 100, in main
    args.func(args)
  File "/usr/local/bin/jss_helper_lib/actions.py", line 541, in promote
    all_packages = jss_connection.Package()
  File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/jamf_software_server.py", line 589, in Package
  File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/jamf_software_server.py", line 734, in get_object
  File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/jamf_software_server.py", line 760, in get_list
  File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/jamf_software_server.py", line 197, in get
  File "/Library/Python/2.7/site-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.9.1-py2.7.egg/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)`

**Comment by krispayne** [comment]
@AllWorkAndNoPlay it's working on my 10.8 server.

Did you go through the old issues and change the TLS/SSL settings?

**Comment by krispayne** [comment]
https://github.com/sheagcraig/jss_helper/issues/23#issuecomment-421139114

**Comment by AllWorkAndNoPlay** [comment]
I changed the
ssl_version=ssl.PROTOCOL_TLSv1
to
ssl_version=ssl.PROTOCOL_TLSv1_2

in 
/Library/Application Support/JSSImporter/jss/tlsadapter.py

still errors

The fallowing files can't be modified, sense they don't exisit. 
/Library/Python/2.7/site-packages/jss/tlsadapter.py
/Library/Python/2.7/site-packages/jss/tlsadapter.pyc
/usr/local/lib/python2.7/site-packages/jss/tlsadapter.py
/usr/local/lib/python2.7/site-packages/jss/tlsadapter.pyc

`jss_helper promote
Traceback (most recent call last):
  File "/usr/local/bin/jss_helper", line 107, in <module>
    main()
  File "/usr/local/bin/jss_helper", line 100, in main
    args.func(args)
  File "/usr/local/bin/jss_helper_lib/actions.py", line 541, in promote
    all_packages = jss_connection.Package()
  File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/jamf_software_server.py", line 589, in Package
  File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/jamf_software_server.py", line 734, in get_object
  File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/jamf_software_server.py", line 760, in get_list
  File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/jamf_software_server.py", line 197, in get
  File "/Library/Python/2.7/site-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.9.1-py2.7.egg/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)`

**Comment by AllWorkAndNoPlay** [comment]
@krispayne had to enable TLSV1_2 and also update the path using https://github.com/sheagcraig/jss_helper/issues/26

**Comment by conor-machugh** [comment]
Fwiw, some of the libraries i found in 

/Library/Python/2.7/site-packages/python_jss-1.5.0-py2.7.egg/jss/

as for some reason i didnt  have a /2.7/jss/ folder

**Comment by grahampugh** [comment]
Hi all, can you try 2.1.0b1? Note that you should already have JSSImporter set up, because this new version relies on the latest python-jss which is installed by JSSImporter.
