### ISSUE TITLE
Cannot pickle Objective-C objects with jss_helper: 2.2.0b3 ++ python-jss: 2.1 

### ISSUE THREAD

**Issue by everetteallen** [jssimporter/jss_helper#28]
Calling jss_helper installs  with any package I know exists is giving me this error every time on macOS 10.15.3

```
Traceback (most recent call last):
  File "/usr/local/bin/jss_helper", line 120, in <module>
    main()
  File "/usr/local/bin/jss_helper", line 113, in main
    func(args)
  File "/usr/local/bin/jss_helper_lib/actions.py", line 637, in get_package_policies
    packages, search, policies)
  File "/usr/local/bin/jss_helper_lib/tools.py", line 215, in find_objects_in_containers
    search_name in search_names) and obj not in results):
  File "/Library/AutoPkg/JSSImporter/jss/jssobject.py", line 142, in __eq__
    return other.__class__ == self.__class__ and str(self) == str(other)
  File "/Library/AutoPkg/JSSImporter/jss/tools.py", line 174, in trigger_cache
    return func(self, *args, **kwargs)
  File "/Library/AutoPkg/JSSImporter/jss/tools.py", line 174, in trigger_cache
    return func(self, *args, **kwargs)
  File "/Library/AutoPkg/JSSImporter/jss/tools.py", line 157, in element_str
    pretty_data = copy.deepcopy(elem)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: Cannot pickle Objective-C objects
```

**Comment by grahampugh** [comment]
Can you show me which command you used please?

**Comment by everetteallen** [comment]
jss_helper installs "NCSU-Campus-NoMADLoginAD-1.3.0-Signed.pkg"

**Comment by everetteallen** [comment]
FWIW same error if I leave off the quotes

**Comment by grahampugh** [comment]
Thanks. I didn't even know there was a command `installs` so I haven't updated that for python3 yet. I'll take a look.
