### ISSUE TITLE
Install help

### ISSUE THREAD

**Issue by rhs615** [jssimporter/jss_helper#8]
Maybe I'm just new to this, but I tried following the package installer and the manual installer and end up with the same results every time I try to run anything, including `"jss_helper -h"`

```
Traceback (most recent call last):
  File "/usr/local/bin/jss_helper", line 107, in <module>
    main()
  File "/usr/local/bin/jss_helper", line 89, in main
    tools.version_check()
  File "/usr/local/bin/jss_helper_lib/tools.py", line 42, in version_check
    python_jss_version = StrictVersion(jss.__version__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/version.py", line 107, in parse
    raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '1.2.0rc2'
```

**Comment by sheagcraig** [comment]
It's not you. I'm surprised-apparently jss_helper installed the release candidate version of python-jss which it is choking on at the version checking stage.

I'm surprised, as I don't think that it should be trying to install a release candidate version over a production version.

You could try dropping into the terminal and running `sudo easy_install https://pypi.python.org/packages/2.7/p/python-jss/python_jss-1.1.0-py2.7.egg#md5=b24823281f0e0c6f7c8270f4e623af4a` and it should hopefully replace 1.2.0rc2 with 1.1.0 until I can fix that distribution snafu.

**Comment by sdicosta** [comment]
If use jss_helper group command everything works fine, and i have the list of my group from server.
But every other command (es:  **_jss_helper computer_**)  return errors : 

_Traceback (most recent call last):
File "/usr/local/bin/jss_helper", line 107, in 
main()
File "/usr/local/bin/jss_helper", line 100, in main
args.func(args)
File "/usr/local/bin/jss_helper_lib/tools.py", line 274, in search_func
results = search_for_object(obj_method, args.search)
File "/usr/local/bin/jss_helper_lib/tools.py", line 127, in search_for_object
results = obj_method()
File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/jamf_software_server.py", line 403, in Computer
File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/jamf_software_server.py", line 734, in get_object
File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/jamf_software_server.py", line 760, in get_list
File "/Library/Python/2.7/site-packages/python_jss-1.4.0-py2.7.egg/jss/jamf_software_server.py", line 197, in get
File "/Library/Python/2.7/site-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 480, in get
return self.request('GET', url, _kwargs)
File "/Library/Python/2.7/site-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 468, in request
resp = self.send(prep, *send_kwargs)
File "/Library/Python/2.7/site-packages/requests-2.9.1-py2.7.egg/requests/sessions.py", line 576, in send
r = adapter.send(request, *_kwargs)
File "/Library/Python/2.7/site-packages/requests-2.9.1-py2.7.egg/requests/adapters.py", line 447, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', ‘SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",)_

Seems something releated to SSL, but why it works fine with group. Is strange.. Isn’t it ?
The JSS user is a Full Administrator with full access.

Thanks
